packages:
  - nfs-utils
  - autofs
  - sssd
  - sssd-ldap
  - sssd-tools
  - openldap-clients
  - oddjob-mkhomedir
  - ncurses
  - ripgrep
  - lsd
  - helix
  - bat

dotfiles:
  helix:
    src: /root/configs/tpad/helix
    dest: /root/.config
  lsd:
    src: /root/configs/tpad/lsd
    dest: /root/.config
  vivid:
    src: /root/configs/tpad/vivid
    dest: /root/.config

clink_hostname_style: green

clink_layout:
    - lbrack
    - hostname
    - rbrack
    - lbrack
    - pwd
    - permission
    - rbrack
    - lparen
    - git
    - rparen
    - symbol

username: root

vivid_theme: ferris
