- name: Enable EPEL and CodeReady Builder on RHEL 9
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "9"
  block:

    - name: Enable CodeReady Builder repository
      ansible.builtin.command:
        cmd: subscription-manager repos --enable codeready-builder-for-rhel-9-{{ ansible_architecture }}-rpms
      changed_when: false

    - name: Import EPEL GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

    - name: Install EPEL
      ansible.builtin.dnf:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
        state: present

