---

- name: Bootstrap 'infra' server
  hosts: infra
  roles:
    - role: clink
      tags: clink

    # Install packages and deploy dotfiles
    - role: baseline
      tags: baseline

    # Set Selinux permissive
    - role: selinux
      tags: selinux
