---

- name: Install packages
  ansible.builtin.dnf:
    name: corosync-qdevice
    state: present

- name: Authenticate cluster on the qdevice host
  ansible.builtin.command:
    argv:
      - pcs
      - host
      - auth
      - "{{ qdevice_host }}"
      - "-u"
      - hacluster
      - "-p"
      - "{{ vault_qdevice_hacluster_password }}"
    delegate_to: "{{ cluster_nodes[0] }}"
    run_once: true

- name: Add qdevice to the cluster
  ansible.builtin.command:
    argv:
      - pcs
      - quorum
      - device
      - add
      - model
      - net
      - "host={{ qdevice_host }}"
      - "algorithm=ffsplit"
    delegate_to: "{{ cluster_nodes[0] }}"
    run_once: true
