---
- name: Set hacluster password
  ansible.builtin.user:
    name: hacluster
    password: "{{ vault_hacluster_password | password_hash('sha512') }}"

- name: Authenticate cluster nodes
  ansible.builtin.command: >
    pcs host auth {{ cluster_nodes | join(' ') }}
    -u hacluster
    -p "{{ vault_hacluster_password }}"
  register: pcs_auth
  changed_when: "'already authorized' not in pcs_auth.stdout"
