---

- name: Install Pacemaker
  import_tasks: install.yml
  tags: install_pacemaker

- name: Setup auth
  import_tasks: auth.yml
  tags: auth

- name: Boostrap
  import_tasks: bootstrap.yml
  tags: bootstrap
