---

- name: Install sbd
  ansible.builtin.dnf:
    name: sbd
    state: present
  notify: restart cluster

- name: Load softdog module
  ansible.builtin.command: modprobe softdog
  changed_when: false

- name: Configure softdog to load at boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/watchdog.conf
    content: |
      softdog
    owner: root
    group: root
    mode: "0644"
  notify: restart cluster

- name: Enable SBD with watchdog timeout
  ansible.builtin.command:
    argv:
      - pcs
      - stonith
      - sbd
      - enable
      - "sbd_watchdog_timeout=35"
  delegate_to: "{{ cluster_nodes[0] }}"
  run_once: true
  notify: restart cluster

# stop/start the cluster won't start the pacemaker service
- name: Ensure pacemaker is enabled and running
  ansible.builtin.systemd:
    name: pacemaker
    enabled: true
    state: started
