---

- name: Install sbd
  ansible.builtin.dnf
    name: sbd
    state: present

- name: Enable and start the sbd service

- name: Configure Watchdog software
  ansible.builtin.command
    modprobe softdog
    echo "softdog" > /etc/modules-load.d/watchdog.conf

- name: Restart the cluster
  ansible.builtin.command
    pcs cluster stop --all
    pcs cluster start --all
